import { chromium } from 'playwright';
const out = process.argv[2];
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PFAD || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const s = await b.newPage({ locale: 'de-AT', timezoneId: 'Europe/Vienna', viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true });
s.on('pageerror', (e) => console.log('FEHLER', e.stack?.split('\n').slice(0,4).join(' | ')));
await s.goto('http://localhost:5199/tools/vorschau/?pfad=/worksheet&rolle=Mitarbeiter', { waitUntil: 'networkidle' });
await s.waitForTimeout(600);
const sel = s.getByLabel('Baustelle', { exact: true });
const opts = await sel.locator('option').allTextContents();
console.log('optionen', opts.slice(0, 4));
const werte = await sel.locator('option').evaluateAll((o) => o.map((x) => x.value).filter(Boolean));
await sel.selectOption(werte[0]);
await s.waitForTimeout(800);
await s.screenshot({ path: `${out}/u-schritt1.png`, fullPage: true });
for (const n of ['Weiter: Material', 'Weiter: Fotos', 'Weiter: Unterschrift']) {
  await s.getByRole('button', { name: n }).click();
  await s.waitForTimeout(300);
}
const kunde = s.getByText('Unterschrift Kunde', { exact: true });
await kunde.scrollIntoViewIfNeeded();
await s.screenshot({ path: `${out}/u-feld-390.png` });
const knoepfe = s.getByRole('button', { name: 'Groß unterschreiben' });
console.log('knöpfe', await knoepfe.count());
const kb = await knoepfe.last().boundingBox();
console.log('knopf', kb);
await knoepfe.last().click();
await s.waitForTimeout(300);
await s.screenshot({ path: `${out}/u-blatt-hoch.png` });
await s.setViewportSize({ width: 844, height: 390 });
await s.waitForTimeout(300);
const c = s.getByRole('dialog').locator('canvas');
const box = await c.boundingBox();
console.log('blatt canvas', box);
await s.mouse.move(box.x + 100, box.y + 150);
await s.mouse.down();
for (let i = 0; i <= 30; i++) await s.mouse.move(box.x + 100 + i * 18, box.y + 150 + Math.sin(i / 3) * 60);
await s.mouse.up();
await s.screenshot({ path: `${out}/u-blatt-quer.png` });
await s.getByRole('button', { name: 'Fertig' }).click();
await s.setViewportSize({ width: 390, height: 844 });
await s.waitForTimeout(400);
await s.getByText('Unterschrift Kunde', { exact: true }).scrollIntoViewIfNeeded();
await s.screenshot({ path: `${out}/u-feld-danach.png` });
console.log('scrollbreite', await s.evaluate(() => [document.documentElement.scrollWidth, innerWidth]));
await b.close();
